/**
 * 
 */
package com.golden.gamedev.object;

import java.awt.Graphics2D;

/**
 * @author MetroidFan2002
 * 
 */
public final class MockBackground extends Background {
	
	/**
	 * Serializable ID generated by Eclipse.
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	 * Creates a new {@link MockBackground} instance.
	 */
	public MockBackground(int w, int h) {
		super();
	}
	
	/**
	 * Creates a new {@link MockBackground} instance.
	 */
	public MockBackground() {
		super();
	}
	
	public void render(Graphics2D g, int xbg, int ybg, int x, int y, int w, int h) {
		super.render(g, xbg, ybg, x, y, w, h);
		g.drawImage(null, x, y, w, h, xbg, ybg, w, h, null);
	}
	
}
