/**
 * 
 */
package com.golden.gamedev;

import java.io.Serializable;

/**
 * The {@link MockActionExecutor} class provides an {@link ActionExecutor}
 * instance for testing purposes only.
 * 
 * @author MetroidFan2002
 * @version 1.0
 * @since 0.2.4
 * @see ActionExecutor
 * 
 */
public final class MockActionExecutor implements ActionExecutor, Serializable {
	
	/**
	 * Serializable ID generated by Eclipse.
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * Whether or not {@link #execute()} has been invoked.
	 */
	public boolean actionExecuted = false;
	
	/**
	 * Creates a new {@link MockActionExecutor} instance.
	 */
	public MockActionExecutor() {
		super();
	}
	
	public void execute() {
		actionExecuted = true;
	}
	
}
